### PR TITLE
Feature/fix public page issue

### PR DESCRIPTION
**Pull request by ICraig-CH**
-removed duplicate check in authentication.js
-added the the fix Mouhajer gave to fix the issue.

### CODE REVIEW

**Review by CH-JonathanBlake — APPROVED** [review]
Approving because these are code improvements but going to stress again that this is a bad solution to the page erroring, we need to understand why there is a null session there.

**Comment by ICraig-CH** [comment]
> Approving because these are code improvements but going to stress again that this is a bad solution to the page erroring, we need to understand why there is a null session there.

I believe its causing an error because in getCachedDataFromSession tries to access pscCache in the session but if you enter directly from a public page the session doesn't exist so it can't use getExtraData on something that doesn't exist and then it errors

**Comment by CH-JonathanBlake** [comment]
> > Approving because these are code improvements but going to stress again that this is a bad solution to the page erroring, we need to understand why there is a null session there.
> 
> I believe its causing an error because in getCachedDataFromSession tries to access pscCache in the session but if you enter directly from a public page the session doesn't exist so it can't use getExtraData on something that doesn't exist and then it errors

However, our understanding of the session middleware is that it should create a session object in every case, and the errors that are popping up in the logs shows that there is an issue related to the session stores.

**Comment by ICraig-CH** [comment]
> > > Approving because these are code improvements but going to stress again that this is a bad solution to the page erroring, we need to understand why there is a null session there.
> > 
> > 
> > I believe its causing an error because in getCachedDataFromSession tries to access pscCache in the session but if you enter directly from a public page the session doesn't exist so it can't use getExtraData on something that doesn't exist and then it errors
> 
> However, our understanding of the session middleware is that it should create a session object in every case, and the errors that are popping up in the logs shows that there is an issue related to the session stores.

I tried looking into that and as far as I got , the cookie parameters we were passing in were fine and the implementation instructions were followed exactly, maybe it might be worth creating a spike for it?

**Review by ch-rfishwick — APPROVED** [review]

**Comment by CH-JonathanBlake** [comment]
> > > > Approving because these are code improvements but going to stress again that this is a bad solution to the page erroring, we need to understand why there is a null session there.
> > > 
> > > 
> > > I believe its causing an error because in getCachedDataFromSession tries to access pscCache in the session but if you enter directly from a public page the session doesn't exist so it can't use getExtraData on something that doesn't exist and then it errors
> > 
> > 
> > However, our understanding of the session middleware is that it should create a session object in every case, and the errors that are popping up in the logs shows that there is an issue related to the session stores.
> 
> I tried looking into that and as far as I got , the cookie parameters we were passing in were fine and the implementation instructions were followed exactly, maybe it might be worth creating a spike for it?

We aren't the team that maintains the middleware, jo gave you a person to follow up with, we just need to speak to them to get their understanding. If they agree its their domain then we update the version after its fixed. If they can find the error is on our side then we fix that.

**Pull request merged**
